version: '3.8'

services:
  xVault:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xVault
    ports:
      - "58951:58951"
    volumes:
      - xVault_data:/app/server
    environment:
      - NODE_ENV=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=58951
      - SERVER_URL=http://localhost:58951
    restart: unless-stopped
    # network_mode: "host" # Ne fonctionne pas correctement sur macOS

volumes:
  xVault_data:
    driver: local
